version: 1
update_configs:
  - package_manager: javascript
    directory: "/"
    update_schedule: "live"
    default_reviewers:
      - gamoutatsumi
    target_branch: "feature"
    version_requirement_updates: increase_versions_if_necessary
