name: textlint
on: 
  pull_request:
    paths:
      - 'content/posts/**/*.md'

jobs:
  textlint:
    name: runner / textlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: textlint
        uses: tsuyoshicho/action-textlint@v2
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          filter_mode: nofilter
          textlint_flags: 'content/posts/**/*.md'
